What does the following error message tell you?

ArgumentError: wrong number of arguments (1 for 2)
  from (irb):1:in `calculate_product'
  from (irb):4
  from /Users/username/.rvm/rubies/ruby-2.5.3/bin/irb:12:in `<main>''

The error message says that you called calculate_product with the wrong number of arguments.
You should have had two but only used one. (1 for 2)
